version: '3.9'
networks:
  laravel:
services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx.dockerfile
    image: nginx:stable
    ports:
      - 8081:80
    volumes:
      - ./:/var/www/html
    links:
      - fpm


  fpm:
    build:
      context: .
      dockerfile: docker/fpm.dockerfile
    volumes:
      - ./:/var/www/html
    links:
      - db

  db:
    image: mysql:8.1.0
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Chaimasassi123
      - MYSQL_DATABASE=jurse2023
    networks:
      - laravel
